### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by mbronckers** [mbronckers/GI-PVI#16]
- [x] Setup UCI Adult dataset
- [x] Setup UCI Bank dataset.
- [ ] Setup MIMIC dataset.
- [x] Write inhomogeneous distribution partition code (different sizing is already done). 
- [x] Decide on hypers settings. 
- [x] Collect initial results.
- [x] Plot results.

- [X] Write PCA plotting code.

**Comment by mbronckers** [comment]
Code:
- [x] Verify MFVI/GI behavior on identical data to plots in Ober et al.
- [x] Evaluate final layer nz's, i.e. t(zs).nz 

Experiments:
- Large precision init in MFVI generally leads to good fitting
- Pick a prior and train until convergence

Writing:
1. Intro
2. Background
3. Related work
4. Unifying PVI & GI (incl. computational analysis)
6. Experiments (incl. implementation)
7. Future directions

**Comment by mbronckers** [comment]
- [x] Plot all results (server mll/acc, client vfe)
- [x] Send email ask for time to meet.
- [x] Send email with results.

- [x] Incorp split B into classification.py
- [x] Run split B experiments.

- [x] Implement dampening.

**Comment by mbronckers** [comment]
Experiments
- [ ] Adult - split B - sequential correct results (no dampening)
- [x] Bank - split B - sequential correct results (no dampening)
- [ ] Bank/Adult Synchronous correct results (dampening)
- [x] MIMIC-III => processing.

Codebase
- [x] Restructure classifcation.py to deal better with configs <=> HPC Workflow improvement
